GROUP_SYSTEM = "http://terminology.hl7.org/CodeSystem/coverage-class"
GROUP_CODE = "group"
PHONE_SYSTEM = "phone"
EMAIL_SYSTEM = "email"
PATIENT_REFERENCE = "Patient"
EXTENTION_URL = "http://example.org/fhir/StructureDefinition/coverage-priority"